### ISSUE TITLE
First compilation support

### ISSUE THREAD

**Issue by CBenghi** [tumcms/Open-Infra-Platform#452]
Hello folks,

I'm trying to compile OIP to help review the paper on Joss.
Although I think I've followed all relevant instructions, I get a ton of CMAKE errors and they are confusing to address.

Would you be willing to give me a hand to get to my first compilation?

Thanks

**Comment by pjanck** [comment]
Invitation sent to your gmail.

**Comment by CBenghi** [comment]
I've added a few minor requests around installation documentation in the joss thread, but I'll close this issue.
Thanks for your help.

**Comment by pjanck** [comment]
Thanks for the comments, I've just seen them. We'll need some time to address them, so I'll get back to you when we're done.

**Comment by CBenghi** [comment]
Thanks.
I'm also finding a few issues in the UI as I try to load some of the models in the repository.
Is that to be expected or did something go wrong with my compilation?

**Comment by pjanck** [comment]
I'm unsure what issues you could be experiencing. 

- Some buttons don't work since they weren't yet connected back to the changed code in the model, but the basic navigation and loading should work. Can you be more explicit?
- Multiple example data cannot be read correctly (especially some complex cases) - but they should all have corresponding issues assigned. Please observe [this table](https://github.com/tumcms/Open-Infra-Platform/blob/development/Documentation/markdown/SupportedIFCrepresentations.md).
